package com.lee.openai.api.chat

import com.fasterxml.jackson.annotation.JsonProperty
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Generated chat message.
 */
public class ChatDelta(
    /**
     * The role of the author of this message.
     *
     * see [ChatRole]
     *
     */
    @JsonProperty("role") var role: String? = null,

    /**
     * The contents of the message.
     */
    @JsonProperty("content") var content: String? = null,

    @JsonProperty("reasoning_content") var reasoningContent: String? = null,

    /**
     * The name and arguments of a function that should be called, as generated by the model.
     */
    @Deprecated(message = "Deprecated in favor of toolCalls")
    @JsonProperty("function_call") var functionCall: FunctionCall? = null,

    /**
     * The tool calls generated by the model, such as function calls.
     */
    @JsonProperty("tool_calls") var toolCalls: List<ToolCallChunk>? = null,

    /**
     * Tool call ID.
     * see [ToolId]
     */
    @JsonProperty("tool_call_id") var toolCallId: String? = null
)