package com.lee.openai.api.chat;

import com.lee.openai.api.core.FinishReason
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A completion generated by OpenAI.
 *
 * [documentation](https://platform.openai.com/docs/api-reference/chat/create)
 */
import com.fasterxml.jackson.annotation.JsonProperty

public class ChatChunk(
    /**
     * Chat choice index.
     */
    @JsonProperty("index") public var index: Int?,
    /**
     * The generated chat message.
     */
    @JsonProperty("delta") public var delta: ChatDelta?,

    /**
     * The reason why OpenAI stopped generating.
     * see [FinishReason]
     */
    @JsonProperty("finish_reason") public var finishReason: String?
)
