package com.lee.openai.api.chat

import com.fasterxml.jackson.annotation.JsonProperty
import com.lee.openai.api.chat.msg.AIChatResponseMessage
import com.lee.openai.api.core.FinishReason

/**
 * A completion generated by OpenAI.
 *
 * [documentation](https://platform.openai.com/docs/api-reference/chat/create)
 */
public data class ChatChoice(
    /**
     * Chat choice index.
     */
    @JsonProperty("index") public val index: Int,
    /**
     * The generated chat message.
     */
    @JsonProperty("message") public val message: AIChatResponseMessage,
    /**
     * The reason why OpenAI stopped generating.
     * see [FinishReason]
     */
    @JsonProperty("finish_reason") public val finishReason: String? = null,
    /**
     * Log probability information for the choice.
     */
    @JsonProperty("logprobs") public val logprobs: Logprobs? = null,
)
